# Generated by Django 4.0.5 on 2022-06-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='variation_valu',
            new_name='variation_value',
        ),
    ]
